apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machines.crd.alpha.io
spec:
  group: crd.alpha.io
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cpu:
                  type: integer 
                memory:
                  type: integer
                storage:
                  type: integer
  names:
    kind: Machine
    plural: machines
  scope: Namespaced
